# Generated by Django 5.0.6 on 2024-06-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('codigoMorador', models.IntegerField()),
                ('ultimaentrada', models.DateTimeField()),
                ('codigoIdentificador', models.IntegerField()),
            ],
        ),
    ]
