# Generated by Django 5.0.6 on 2024-08-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0002_visitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='moradores',
            name='responsavel',
            field=models.BooleanField(default=False),
        ),
    ]
