# Generated by Django 5.0.6 on 2025-04-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0003_moradores_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='moradores',
            name='codigoCondominio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='codigoCondominio',
            field=models.IntegerField(default=0),
        ),
    ]
