# Generated by Django 5.0.6 on 2024-06-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelsArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('tipo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='modelsAreaManuntencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=255)),
                ('ultimamanutencao', models.DateField()),
                ('proximamanutencao', models.DateField()),
                ('statusServico', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='modelsReservasArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('moradorId', models.IntegerField(default=0)),
                ('areaNome', models.CharField(max_length=255)),
                ('dataReserva', models.DateField()),
                ('horarioReserva', models.TimeField()),
                ('tempoTotal', models.IntegerField(default=3)),
            ],
        ),
    ]
