# Generated by Django 5.0.6 on 2024-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areacondominio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsreservasarea',
            name='tiporeserva',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
