# Generated by Django 5.0.6 on 2024-08-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areacondominio', '0002_modelsreservasarea_tiporeserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsarea',
            name='condominioCodigo',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='modelsareamanuntencao',
            name='condominioCodigo',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='modelsreservasarea',
            name='condominioCodigo',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
