# Generated by Django 5.0.6 on 2024-06-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoEmprestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoObjeto', models.IntegerField()),
                ('codigoProprietario', models.IntegerField()),
                ('codigoPrestamista', models.IntegerField()),
                ('dataehora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioPrivadoUtensilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('proprietario', models.IntegerField(default=0)),
                ('tipo_objeto', models.CharField(max_length=255)),
                ('emprestado', models.BooleanField(default=False)),
                ('emprestadoaquem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
