# Generated by Django 5.0.6 on 2024-06-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatrimonioPrivadoUtensilio',
            new_name='PatrimonioPrivadoCompartilhaveis',
        ),
    ]
