# Generated by Django 5.0.6 on 2024-08-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_veiculo_patrimoniopublico_codigomorador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default='0'),
        ),
    ]
